name: Generate Sitemap

on:
  push:
    branches:
      - main   # eller 'master' om din default branch heter så
  workflow_dispatch: # gör att du kan köra den manuellt också

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: "https://smideskurser.se"

      - name: Commit and push sitemap
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add sitemap.xml
          git commit -m "Update sitemap.xml"
          git push
